name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y expect
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install watchdog pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests
